#Make sure this URL matches your current launch profile.
@DeveloperAuthorizer = http://localhost:5001

@UserName = HackerMan2000
#Generate a token with the specified username and the role "Developer".
GET {{DeveloperAuthorizer}}/auth/{{UserName}}
Accept: text/plain

###
